import Head from 'next/head'
import { Header, Footer, Blog, Possibility, What, Features } from '../containers'
import { Brand, CTA, Navbar } from '../components'
import styles from '../styles/index.module.css'

export default function Home() {
  return (
    <div className="App">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='gradient__bg'>
        <Navbar />
        <Header />
      </div>
      <Brand />
      <What />
      <Features />
      <Possibility />
      <CTA />
      <Blog />
      <Footer />

    </div>
  )
}
